Seperated and Added to the Linux and Andriod Install Pages
brave/brave-browser pull request #38942
Opened 2024-06-11 03:19 UTC by alanakihn

Resolves #38572 

Submitter Checklist:

- [ ]  I confirm that no security/privacy review is needed, or that I have requested one
- [ ] There is a ticket for my issue
- [ ] Used Github auto-closing keywords in the PR description above
- [ ] Wrote a good PR/commit description
- [ ] Added appropriate labels (QA/Yes or QA/No; release-notes/include or release-notes/exclude; OS/...) to the associated issue
- [ ] Checked the PR locally: npm run test -- brave_browser_tests, npm run test -- brave_unit_tests, npm run lint, npm run gn_check, npm run tslint
- [ ] Ran git rebase master (if needed)

I separated the Linux and Android install pages as to provide more clarity for developers targeting these operating systems. I also added some additional information for more Linux distributions and a short guide on setting up the Android emulator. This is addressing the open issue: #38572. 

Currently I have added the two files  in the home directory as markdown files, as I don't have permission to edit the Wiki directly.

2024-10-04 07:10 UTC, hamirmahal requested changes

2024-10-04 07:10 UTC, hamirmahal commented on Linux.md
> +## Additonal installs for different Linux distributions:
```suggestion
## Additional installs for different Linux distributions: 
```

2024-10-04 16:08 UTC, hamirmahal requested changes

2024-10-04 16:08 UTC, hamirmahal commented on Linux.md
> +## Additonal installs for different Linux distributions:
```suggestion
## Additional installs for different Linux distributions: 
```

2024-11-10 22:47 UTC, yyyhko approved these changes

2024-12-27 22:26 UTC, firoj0 commented
Hello world

2025-01-08 11:25 UTC, closed without merging

2025-01-08 11:25 UTC, mihaiplesa commented
Closing this as it's stale and now that Android development can happen on macOS also it does deserve its separate wiki.