Release Notes for iOS Release 1.66.113
brave/brave-browser pull request #39332
Opened 2024-06-24 22:37 UTC by Uni-verse

Resolves [#38470](https://github.com/brave/brave-browser/issues/38470)

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A
  - [ ] https://github.com/brave/brave-browser/wiki/Brave-Wallet

## Test Plan:
N/A

2024-07-01 17:02 UTC, srirambv requested changes

2024-07-01 17:02 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Added support to retry, cancel and speed up transactions. ([#36627](https://github.com/brave/brave-browser/issues/36627))
maybe capitalize Retry/Cancel/Speed Up

2024-07-01 17:02 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Fixed toggle being missing when importing an existing Wallet. ([#38123](https://github.com/brave/brave-browser/issues/38123))
`Fixed missing import legacy wallet option when when restoring wallet in onboarding`

2024-07-02 22:16 UTC, kjozwiak requested changes
Some small nits but looking good 👍

2024-07-02 22:16 UTC, kjozwiak commented on CHANGELOG_iOS.md
> + - Implemented using cached ad-blocking results after changing Shield settings. ([#37090](https://github.com/brave/brave-browser/issues/37090))
nit: Only use `Shields` as a capital when also mentioning `Brave`. For example: `Brave Shields`. But we usually just use it as a lower case. For example:

```
 - Implemented using cached ad-blocking results after changing shields settings. ([#37090](https://github.com/brave/brave-browser/issues/37090))
```

2024-07-02 22:16 UTC, kjozwiak commented on CHANGELOG_iOS.md
> + - Added Brave Browser to be an AutoFill Provider. ([#36028](https://github.com/brave/brave-browser/issues/36028))
nit: Probably don't need to mention `Browser`. Can just use the following:

```
- Added Brave to be an AutoFill Provider. ([#36028](https://github.com/brave/brave-browser/issues/36028))
```

2024-07-02 22:16 UTC, kjozwiak commented on CHANGELOG_iOS.md
> + - Added Claude 3 Haiku and Claude 3 Sonnet model support for Leo. ([#36802](https://github.com/brave/brave-browser/issues/36802))
This line should be at the top rather than near the middle as it ads new model support etc.. Note looks fine, just need to change the positioning.

2024-07-05 17:56 UTC, kjozwiak approved these changes
LGTM 👍

2024-07-10 05:01 UTC, srirambv requested changes
once the extra when is removed its good to merge

2024-07-10 05:01 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Fixed missing import legacy wallet option when when restoring wallet in onboarding. ([#38123](https://github.com/brave/brave-browser/issues/38123))
remove one `when`

2024-07-11 17:26 UTC, Uni-verse commented on CHANGELOG_iOS.md
> + - Fixed missing import legacy wallet option when when restoring wallet in onboarding. ([#38123](https://github.com/brave/brave-browser/issues/38123))
Oops, good catch. Thanks.

2024-07-15 03:52 UTC, srirambv approved these changes

2024-07-15 03:52 UTC, merged