Add Release Notes for iOS Release 1.68.134
brave/brave-browser pull request #41015
Opened 2024-09-11 21:27 UTC by Uni-verse

Resolves https://github.com/brave/brave-browser/issues/41013

## Submitter Checklist:

- [x] I confirm that no security/privacy review [is needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or that I have [requested](https://github.com/brave/security/issues/new/choose) one
- [x] There is a [ticket](https://github.com/brave/brave-browser/issues) for my issue
- [x] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [x] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [x] Added appropriate labels (`QA/Yes` or `QA/No`; `release-notes/include` or `release-notes/exclude`; `OS/...`) to the associated issue
- [ ] Checked the PR locally: `npm run test -- brave_browser_tests`, `npm run test -- brave_unit_tests`, `npm run lint`, `npm run gn_check`, `npm run tslint`
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] A security review [is not needed](https://github.com/brave/brave-browser/wiki/Security-reviews), or a link to one is included in the PR description
- [ ] New files have MPL-2.0 license header
- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Changes in component dependencies are properly reflected in `gn`
- [ ] Code follows the [style guide](https://chromium.googlesource.com/chromium/src/+/HEAD/styleguide/c++/c++.md)
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] The associated issue milestone is set to the smallest version that the
  changes has landed on
- [ ] All relevant documentation has been updated, for instance:
  - [ ] https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)
  - [ ] https://github.com/brave/brave-browser/wiki/Proxy-redirected-URLs
  - [ ] https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections
  - [ ] https://github.com/brave/brave-browser/wiki/Brave%E2%80%99s-Use-of-Referral-Codes
  - [ ] https://github.com/brave/brave-browser/wiki/Custom-Headers
  - [ ] https://github.com/brave/brave-browser/wiki/Web-Compatibility-Exceptions-in-Brave
  - [ ] https://github.com/brave/brave-browser/wiki/QA-Guide
  - [ ] https://github.com/brave/brave-browser/wiki/P3A
  - [ ] https://github.com/brave/brave-browser/wiki/Brave-Wallet

## Test Plan:
N/A

2024-09-12 06:16 UTC, srirambv requested changes
Once change its a good to go for Web3

2024-09-12 06:16 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Added the ability to send BTC on “Send” screen. ([#37958](https://github.com/brave/brave-browser/issues/37958))
Update to  `Added support to "Send" BTC from iOS.`

2024-09-12 06:16 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Updated default account names to differentiate between mainnet and testnet accounts. ([#38526](https://github.com/brave/brave-browser/issues/38526))
Specific change to Filecoin so better to add that 
`Updated default account names to differentiate between Filecoin mainnet and testnet accounts.`

2024-09-12 06:16 UTC, srirambv commented on CHANGELOG_iOS.md
> + - Updated “Show Zero Balances” button to always be displayed in “Select a Token to Send” screen. ([#38452](https://github.com/brave/brave-browser/issues/38452))
Maybe change to 
`Updated “Show Zero Balances” button to be always shown on "Select a Token to Send” screen.`

2024-09-16 17:24 UTC, kjozwiak commented on CHANGELOG_iOS.md
> + - Updated ads service preferences to disable fetching when Brave Reward/Brave News is disabled. ([#39621](https://github.com/brave/brave-browser/issues/39621))
nit: `Brave Reward` --> `Brave Rewards`

2024-09-16 18:19 UTC, Uni-verse commented
> Once change its a good to go for Web3

Thank you for reviewing @srirambv 

https://github.com/brave/brave-browser/commit/b08f0f8e85586a9effd8a1972d9223f00dae9332

2024-09-16 18:22 UTC, Uni-verse commented on CHANGELOG_iOS.md
> + - Fixed buttons not working to dismiss the Premium upgrade card in Leo chat. ([#39061](https://github.com/brave/brave-browser/issues/39061))
Yeah thanks, I'm also not certain. You're probably right.

2024-09-16 18:24 UTC, Uni-verse commented
> There's a few nit but generally looks good 👍

Thanks for reviewing!
https://github.com/brave/brave-browser/commit/8354fbe77b5942c1eb00beda467e8812a67ac596

2024-09-16 18:28 UTC, kylehickinson approved these changes

2024-09-16 20:59 UTC, kjozwiak approved these changes
LGMT 👍

2024-09-17 11:51 UTC, srirambv approved these changes
++

2024-09-17 11:51 UTC, merged